---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- target:
    kind: Job
    name: observability-setup
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ebdnquay.ebdnlab.vmware.tamlab.rdu2.redhat.com:8443/redhat-v414/openshift4/ose-cli:e11912cb

