apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
# Change the Subscription details
- target:
    kind: MultiClusterHub
    name: .*
  patch: |-
    - op: replace
      path: /metadata/annotations/installer.open-cluster-management.io/mce-subscription-spec
      value: '{"source": "my-redhat-v413-catalog"}'

