apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
- target:
    kind: Subscription
    name: .*
  patch: |-
    - op: replace
      path: /spec/channel
      value: stable
    - op: replace
      path: /spec/source
      value: cs-my-redhat-catalog
