apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - operator: Exists
      effect: NoSchedule 
      key: node-role.kubernetes.io/infra
    - operator: Exists
      effect: NoExecute
      key: node-role.kubernetes.io/infra

