apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-eck
  namespace: elastic
spec:
  version: 8.13.2
  image: quay.devu.ca:8443/elasticstack/elasticsearch:8.13.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
