apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nutanix-csi-operator
  namespace: openshift-cluster-csi-drivers
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: nutanixcsioperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
