apiVersion: v1
kind: Namespace
metadata:
  name: elastic
  annotations:
    openshift.io/node-selector: 'node-role.kubernetes.io/eck='
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/eck"},{"operator": "Exists", "effect": "NoExecute", "key": "node-role.kubernetes.io/eck"}]
