apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
# Change the Subscription details
- target:
    kind: Subscription
    name: .*
  patch: |-
    - op: replace
      path: /spec/channel
      value: release-2.9
    - op: replace
      path: /spec/source
      value: cs-my-redhat-catalog

