apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "SSO project"
    openshift.io/display-name: "Red Hat SSO"
    openshift.io/node-selector: 'node-role.kubernetes.io/infra='
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/infra"},{"operator": "Exists", "effect": "NoExecute", "key": "node-role.kubernetes.io/infra"}
      ]
  name: sso
