apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scc:restricted:users
  namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:restricted
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-storage
