apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator-subscription
  namespace: openshift-storage
spec:
  channel: stable-4.13
  installPlanApproval: Automatic
  name: odf-operator
  source: my-redhat-v413-catalog
  sourceNamespace: openshift-marketplace
