apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
# Change the Subscription details
- target:
    kind: Subscription
    name: .*
  patch: |-
    - op: replace
      path: /spec/channel
      value: ebdn-stable
    - op: replace
      path: /spec/source
      value: ebdn-cs-my-redhat-catalog
- target:
    kind: Job
    name: create-cluster-init-bundle
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ebdn-ebdnquay.ebdnlab.vmware.tamlab.rdu2.redhat.com:8443/redhat-v414/openshift4/ose-cli:e11912cb


