apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# Change the namespace NAME
patches:
- target:
    kind: Namespace
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: open-cluster-management

# Cgange the Subscription details
- target:
    kind: Subscription
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: open-cluster-management
    - op: replace
      path: /metadata/namespace
      value: open-cluster-management
    - op: replace
      path: /spec/channel
      value: release-2.8
    - op: replace
      path: /spec/name
      value: advanced-cluster-management
    - op: replace
      path: /spec/source
      value: my-redhat-v413-catalog

