apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
# Change the Subscription details
- target:
    kind: StorageClass
    name: .*
  patch: |-
    - op: replace
      path: /parameters/dataServiceEndPoint
      value: 10.10.17.20:3260
    - op: replace
      path: /parameters/storageContainer
      value: storage-name
- target:
    kind: Secret
    name: .*
  patch: |-
    - op: replace
      path: /stringData/key
      value: 10.10.17.90:9440:username:password
