apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Exists
    type: vector
  logStore:
    elasticsearch:
      resources:
        requests:
          memory: 2Gi
      storage:
        size: 200G
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
    lokistack:
      name: lokistack-instance
    retentionPolicy:
      application:
        maxAge: 7d
        pruneNamespacesInterval: 7d
    type: lokistack
  visualization:
    kibana:
      replicas: 1
    type: ocp-console
  managementState: Managed

