---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: acm-cli-job-sa-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
  - apiGroups:
      - objectbucket.io
    resources:
      - objectbucketclaims
    verbs:
      - get
      - list
      - create
      - patch
